# Starter pipeline
- task: CmdLine@2
  inputs:
    script: |
      git clone https://github.com/octopus199/octopus.git
      git config --global user.name "kochkaev"
      git checkout master
      git add .
      git commit -m "abc"
      git push https://{AzureDevopsPAT}@dev.azure.com/{org}/{pro}/_git/delete.git
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
